### ISSUE TITLE
Escenario - Gestión de Taladros- Mantenimiento

### ISSUE THREAD

**Issue by pereirajangel** [Spontecorp-CA/Sismon_6#105]
MANTENIMIENTO
El botón guardar se activa de una vez, cuando pones la fecha y el número de días.
Debería activar sólo botón agregar, para luego que esté agregado en la lista de mantenimientos y hacer entonces "guardar".

**Comment by jgcastillo** [comment]
Se modificó la lógica de habilitación de los botones y se cambió el evento de selección del escenario
