### ISSUE TITLE
Escenarios - Perforar Escenario

### ISSUE THREAD

**Issue by pereirajangel** [Spontecorp-CA/Sismon_6#107]
Por alguna desconocida, vericueta y extraña razón... al hacer "Perforar Escenario" dio un error
NullPointerException.

Rehice la BD, cargué la data, agregue los mantenimientos de taladros, NO hice mover, descontinuar, ni agregar.....y corrió sin problemas.

**Comment by jgcastillo** [comment]
No se pudo reproducir el error
